# Generated by Django 6.0.7 on 2026-07-20 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('destination', models.CharField(choices=[('مكة', 'مكة'), ('المدينة', 'المدينة'), ('مكة والمدينة', 'مكة والمدينة')], max_length=30)),
                ('trip_duration', models.CharField(max_length=50)),
                ('hotel_name', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('pilgrims_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
