# Generated by Django 6.0.7 on 2026-07-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_trip_delete_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='hotel_name',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='pilgrims_count',
            new_name='pilgrims',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
    ]
