# Generated by Django 6.0.7 on 2026-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_rename_trip_duration_trip_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='pilgrims',
            new_name='seats',
        ),
        migrations.AddField(
            model_name='trip',
            name='airline',
            field=models.CharField(default='غير محدد', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
