# Generated by Django 6.0.7 on 2026-07-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pilgrims',
        ),
        migrations.AddField(
            model_name='customer',
            name='room_type',
            field=models.CharField(choices=[('فردية', 'فردية'), ('ثنائية', 'ثنائية'), ('ثلاثية', 'ثلاثية'), ('رباعية', 'رباعية')], default='رباعية', max_length=20),
        ),
    ]
