# Generated by Django 6.0.7 on 2026-07-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_remove_customer_pilgrims_customer_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='price',
            new_name='double_price',
        ),
        migrations.AddField(
            model_name='trip',
            name='quad_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='quint_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='triple_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='room_type',
            field=models.CharField(choices=[('ثنائية', 'ثنائية'), ('ثلاثية', 'ثلاثية'), ('رباعية', 'رباعية'), ('خماسية', 'خماسية')], default='رباعية', max_length=20),
        ),
    ]
