# Generated by Django 6.0.7 on 2026-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_agencysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='guide_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trip',
            name='stop_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('مباشرة', 'مباشرة'), ('غير مباشرة', 'غير مباشرة')], default='مباشرة', max_length=20),
        ),
    ]
