# Generated by Django 6.0.7 on 2026-07-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_trip_guide_name_trip_stop_city_trip_trip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('ثنائية', 'ثنائية'), ('ثلاثية', 'ثلاثية'), ('رباعية', 'رباعية'), ('خماسية', 'خماسية')], max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='packages.trip')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='packages.room'),
        ),
    ]
