# Generated by Django 6.0.7 on 2026-07-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_room_customer_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='group_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
