# Generated by Django 6.0.7 on 2026-07-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('طيران', 'طيران'), ('فندق', 'فندق'), ('نقل', 'نقل'), ('فيزا', 'فيزا'), ('إشهار', 'إشهار'), ('رواتب', 'رواتب'), ('مكتب', 'مكتب'), ('أخرى', 'أخرى')], default='أخرى', max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='packages.trip'),
        ),
    ]
