# Generated by Django 6.0.7 on 2026-09-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_customer_commission_customerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=150),
        ),
    ]
