# Generated by Django 6.0.7 on 2026-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_supportmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='financial_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
