# Generated by Django 6.0.7 on 2026-08-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_subscription_is_active_subscription_lifetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinforequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
